"""
The workshop's category taxonomy and specification vocabulary.

A category is a materialized path on the product and there is no categories table,
so a branch nobody has filed into has no row anywhere -- which means it cannot be
offered while filing, and the first product into every branch would be typed by
hand.  That is precisely where ``electronics/microcontrollers`` on Monday and
``electronic components/dev boards`` on Thursday come from.

These constants are what the application offers *in addition to* the paths products
already carry.  They create nothing: a branch listed here and occupied by no product
still has no row, and a path in use that is absent from here is still returned by
every query.  The list is a set of suggestions with the weight of a decision behind
it, not a whitelist -- ``CatalogService`` accepts a path from outside it, because a
taxonomy that refuses the thing in your hand is worse than none.

``docs/category-taxonomy.md`` is the authority.  It carries the one-line definition
of every branch, the rules that decide the hard cases, and the reasoning; this module
carries only the strings.  ``tests/unit/test_catalog_taxonomy.py`` asserts the two
agree, which is what makes a change to one without the other a failing test rather
than a slow divergence.  Renaming a branch means editing both, and the products that
carry the old path, in the same change.

Specification keys are pinned for a sharper reason: ``rename_category`` and
``rename_tag`` exist and there is no ``rename_specification``, so ``Thread`` beside
``Thread Size`` cannot be repaired in bulk once both are in use.  Prevention is the
only mechanism available.

Pure module: standard library only.  No Flask, no database, no file I/O.
"""

# Every branch of the record: roots, intermediate parents and leaves.  Parents are
# included deliberately.  They are legitimate filing targets when the leaf is not yet
# known, and ``category_tree`` derives one entry per distinct path -- so without them
# a catalog whose only product sits three levels deep renders a tree with holes above
# it.
CATEGORY_PATHS: tuple[str, ...] = (
    "electrical",
    "electrical/boxes & enclosures",
    "electrical/cable management",
    "electrical/circuit protection",
    "electrical/circuit protection/breakers & disconnects",
    "electrical/circuit protection/fuses & holders",
    "electrical/conduit & raceway",
    "electrical/conduit & raceway/emt",
    "electrical/conduit & raceway/fittings",
    "electrical/conduit & raceway/flexible & liquid-tight",
    "electrical/conduit & raceway/pvc & ent",
    "electrical/conduit & raceway/straps & clamps",
    "electrical/conduit & raceway/surface raceway",
    "electrical/cords & plugs",
    "electrical/cords & plugs/iec cords & inlets",
    "electrical/cords & plugs/pdus & splitters",
    "electrical/cords & plugs/plugs & connector bodies",
    "electrical/cords & plugs/strain reliefs & glands",
    "electrical/data & network cabling",
    "electrical/data & network cabling/bulk cable",
    "electrical/data & network cabling/coax",
    "electrical/data & network cabling/jacks & keystone",
    "electrical/data & network cabling/patch cables",
    "electrical/devices",
    "electrical/devices/receptacles",
    "electrical/devices/switches",
    "electrical/insulation & sleeving",
    "electrical/lighting",
    "electrical/lighting/bulbs & lamps",
    "electrical/lighting/fixtures",
    "electrical/lighting/lampholders & sockets",
    "electrical/motor & appliance parts",
    "electrical/wall plates & covers",
    "electrical/wire & cable",
    "electrical/wire connectors",
    "electrical/wire connectors/crimp splices & sleeves",
    "electrical/wire connectors/lugs & grounding",
    "electrical/wire connectors/wire nuts & lever connectors",
    "electronics",
    "electronics/access control",
    "electronics/actuators",
    "electronics/actuators/motor drivers",
    "electronics/actuators/motors",
    "electronics/actuators/pumps & fans",
    "electronics/actuators/solenoids",
    "electronics/actuators/thermal",
    "electronics/cables & adapters",
    "electronics/cables & adapters/audio",
    "electronics/cables & adapters/data & serial",
    "electronics/cables & adapters/usb",
    "electronics/cables & adapters/video",
    "electronics/components",
    "electronics/components/capacitors",
    "electronics/components/diodes",
    "electronics/components/filters & ferrites",
    "electronics/components/integrated circuits",
    "electronics/components/resistors",
    "electronics/components/transistors",
    "electronics/computing & storage",
    "electronics/computing & storage/docks & adapters",
    "electronics/computing & storage/drives & media",
    "electronics/computing & storage/pc parts & peripherals",
    "electronics/connectors",
    "electronics/connectors/banana & binding posts",
    "electronics/connectors/barrel & power",
    "electronics/connectors/circular & waterproof",
    "electronics/connectors/dupont & jst",
    "electronics/connectors/headers",
    "electronics/connectors/usb",
    "electronics/dev boards",
    "electronics/dev boards/arduino",
    "electronics/dev boards/esp32 & esp8266",
    "electronics/dev boards/other boards",
    "electronics/dev boards/raspberry pi",
    "electronics/displays & indicators",
    "electronics/displays & indicators/displays",
    "electronics/displays & indicators/indicators & buzzers",
    "electronics/displays & indicators/leds",
    "electronics/displays & indicators/panel meters",
    "electronics/enclosures & mounting",
    "electronics/modules & breakouts",
    "electronics/networking",
    "electronics/power",
    "electronics/power/batteries",
    "electronics/power/battery holders & chargers",
    "electronics/power/dc-dc converters",
    "electronics/power/distribution & din rail",
    "electronics/power/power supplies",
    "electronics/prototyping",
    "electronics/relays & control",
    "electronics/relays & control/relays & contactors",
    "electronics/relays & control/timers & counters",
    "electronics/sensors",
    "electronics/sensors/current & voltage",
    "electronics/sensors/proximity & distance",
    "electronics/sensors/temperature & humidity",
    "electronics/sensors/water & environmental",
    "electronics/soldering & rework",
    "electronics/switches & inputs",
    "electronics/switches & inputs/buttons & switches",
    "electronics/switches & inputs/knobs & encoders",
    "electronics/switches & inputs/limit switches",
    "electronics/test & measurement",
    "electronics/wire & terminations",
    "electronics/wire & terminations/hookup wire",
    "electronics/wire & terminations/jumper wires",
    "electronics/wire & terminations/ribbon cable",
    "electronics/wire & terminations/terminals & crimps",
    "fasteners",
    "fasteners/anchors",
    "fasteners/anchors/drywall anchors",
    "fasteners/anchors/masonry anchors",
    "fasteners/hooks & hangers",
    "fasteners/machine screws & bolts",
    "fasteners/machine screws & bolts/button head",
    "fasteners/machine screws & bolts/carriage bolts",
    "fasteners/machine screws & bolts/flat head & countersunk",
    "fasteners/machine screws & bolts/hex head",
    "fasteners/machine screws & bolts/pan & round head",
    "fasteners/machine screws & bolts/set screws",
    "fasteners/machine screws & bolts/socket head cap",
    "fasteners/machine screws & bolts/thumb screws",
    "fasteners/nails & staples",
    "fasteners/nails & staples/collated & air fasteners",
    "fasteners/nails & staples/nails",
    "fasteners/nails & staples/staples & tacks",
    "fasteners/nuts",
    "fasteners/pins & clips",
    "fasteners/rivets",
    "fasteners/self-tapping screws",
    "fasteners/standoffs & spacers",
    "fasteners/structural connectors",
    "fasteners/threaded inserts",
    "fasteners/washers",
    "fasteners/wood & construction screws",
    "fasteners/wood & construction screws/construction screws",
    "fasteners/wood & construction screws/deck screws",
    "fasteners/wood & construction screws/drywall screws",
    "fasteners/wood & construction screws/lag screws",
    "fasteners/wood & construction screws/structural screws",
    "fasteners/wood & construction screws/trim & cabinet screws",
    "fasteners/wood & construction screws/wood screws",
)

# The specification keys the record expects, across every branch family.  A key is
# added here when the record adds it, never while filing a product.
SPECIFICATION_KEYS: tuple[str, ...] = (
    "Amperage",
    "Capacity",
    "Category",
    "Chemistry",
    "Chipset",
    "Coil Voltage",
    "Color",
    "Conductors",
    "Connectivity",
    "Contact Rating",
    "Drive",
    "Ends",
    "Flash",
    "Gauge",
    "Gender",
    "Input Voltage",
    "Interface",
    "Length",
    "Material",
    "Output Current",
    "Output Voltage",
    "PSRAM",
    "Package",
    "Pitch",
    "Poles",
    "Positions",
    "Range",
    "Series",
    "Shaft",
    "Shielding",
    "Size",
    "Substrate",
    "Supply Voltage",
    "Thread",
    "Tolerance",
    "Trade Size",
    "Type",
    "Value",
    "Voltage",
)
