"""Add materials taxonomy table

Revision ID: 5d61d892776a
Revises: 6e64cd1f734a
Create Date: 2025-09-11 10:04:20.759861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d61d892776a'
down_revision: Union[str, None] = '6e64cd1f734a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_taxonomy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent', sa.String(length=100), nullable=True),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.CheckConstraint('NOT (level = 1 AND parent IS NOT NULL)', name='ck_category_no_parent'),
    sa.CheckConstraint('level >= 1 AND level <= 3', name='ck_valid_level'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_taxonomy_active'), 'material_taxonomy', ['active'], unique=False)
    op.create_index(op.f('ix_material_taxonomy_level'), 'material_taxonomy', ['level'], unique=False)
    op.create_index(op.f('ix_material_taxonomy_name'), 'material_taxonomy', ['name'], unique=True)
    op.create_index(op.f('ix_material_taxonomy_parent'), 'material_taxonomy', ['parent'], unique=False)
    op.create_index(op.f('ix_material_taxonomy_sort_order'), 'material_taxonomy', ['sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_taxonomy_sort_order'), table_name='material_taxonomy')
    op.drop_index(op.f('ix_material_taxonomy_parent'), table_name='material_taxonomy')
    op.drop_index(op.f('ix_material_taxonomy_name'), table_name='material_taxonomy')
    op.drop_index(op.f('ix_material_taxonomy_level'), table_name='material_taxonomy')
    op.drop_index(op.f('ix_material_taxonomy_active'), table_name='material_taxonomy')
    op.drop_table('material_taxonomy')
    # ### end Alembic commands ###
