"""add_item_photos_table

Revision ID: 649ff0d93d25
Revises: 3b7d76c3fb8d
Create Date: 2025-09-18 16:57:25.976839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '649ff0d93d25'
down_revision: Union[str, None] = '3b7d76c3fb8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ja_id', sa.String(length=10), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('thumbnail_data', sa.LargeBinary(), nullable=False),
    sa.Column('medium_data', sa.LargeBinary(), nullable=False),
    sa.Column('original_data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("ja_id REGEXP '^JA[0-9]{6}$'", name='ck_photo_valid_ja_id_format'),
    sa.CheckConstraint('file_size > 0', name='ck_photo_positive_file_size'),
    sa.CheckConstraint("content_type IN ('image/jpeg', 'image/png', 'image/webp', 'application/pdf')", name='ck_photo_valid_content_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_photos_ja_id'), 'item_photos', ['ja_id'], unique=False)
    op.create_index(op.f('ix_item_photos_created_at'), 'item_photos', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_photos_created_at'), table_name='item_photos')
    op.drop_index(op.f('ix_item_photos_ja_id'), table_name='item_photos')
    op.drop_table('item_photos')
    # ### end Alembic commands ###
