"""Initial database schema

Revision ID: 6e64cd1f734a
Revises: 
Create Date: 2025-09-11 10:00:07.574780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e64cd1f734a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ja_id', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('length', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('width', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('thickness', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('wall_thickness', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('shape', sa.String(length=50), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=False),
    sa.Column('thread_series', sa.String(length=10), nullable=True),
    sa.Column('thread_handedness', sa.String(length=10), nullable=True),
    sa.Column('thread_size', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('sub_location', sa.String(length=100), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchase_location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('vendor_part', sa.String(length=100), nullable=True),
    sa.Column('original_material', sa.String(length=100), nullable=True),
    sa.Column('original_thread', sa.String(length=50), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.CheckConstraint("ja_id REGEXP '^JA[0-9]{6}$'", name='ck_valid_ja_id_format'),
    sa.CheckConstraint('length IS NULL OR length > 0', name='ck_positive_length'),
    sa.CheckConstraint('quantity > 0', name='ck_positive_quantity'),
    sa.CheckConstraint('thickness IS NULL OR thickness > 0', name='ck_positive_thickness'),
    sa.CheckConstraint('wall_thickness IS NULL OR wall_thickness > 0', name='ck_positive_wall_thickness'),
    sa.CheckConstraint('weight IS NULL OR weight > 0', name='ck_positive_weight'),
    sa.CheckConstraint('width IS NULL OR width > 0', name='ck_positive_width'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ja_id', 'active', name='uq_ja_id_active')
    )
    op.create_index(op.f('ix_inventory_items_active'), 'inventory_items', ['active'], unique=False)
    op.create_index(op.f('ix_inventory_items_ja_id'), 'inventory_items', ['ja_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_items_ja_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_active'), table_name='inventory_items')
    op.drop_table('inventory_items')
    # ### end Alembic commands ###
